#FROM osmhpi/cohydra:latest
FROM osmhpi/cohydra:dev


#RUN apt-get update && apt-get -y install \
#            apt-transport-https \
#            ca-certificates \
#            curl \
#            software-properties-common \
#            gnupg


#add docker 
#RUN curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -


#architecture => dpkg --print-architecture
#Distributor => lsb_release -is
#Codename => lsb_release -cs

#RUN add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian  buster  stable" 

#RUN apt-get update && apt-get -y install docker-ce-cli
